config/routes.rb
Orgup::Application.routes.draw do
	devise_for :members
	resources :members

  root :to => 'members#index'
end

app/models/member.rb
class Member < ActiveRecord::Base
	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
	before_filter :authenticate_member!
end

app/controllers/members_controller.rb
class MembersController < InheritedResources::Base
	def index
		redirect_to member_path(current_member)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Orgup</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/members/_form.html.slim
= form_for @member do |f|
  - if @member.errors.any?
    #error_explanation
      h2 = "#{pluralize(@member.errors.count, "error")} prohibited this member from being saved:"
      ul
        - @member.errors.full_messages.each do |message|
          li = message

  .actions = f.submit 'Save'

app/views/members/edit.html.slim
h1 Editing member

== render 'form'

= link_to 'Show', @member
'|
= link_to 'Back', members_path

app/views/members/index.html.slim
h1 Listing members

table
  tr
    th
    th
    th

  - @members.each do |member|
    tr
      td = link_to 'Show', member
      td = link_to 'Edit', edit_member_path(member)
      td = link_to 'Destroy', member, :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New Member', new_member_path

app/views/members/new.html.slim
h1 New member

== render 'form'

= link_to 'Back', members_path

app/views/members/show.html.slim
p#notice = notice


= link_to 'Edit', edit_member_path(@member)
'|
= link_to 'Back', members_path